# Generated by Django 4.0.4 on 2022-06-06 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_author_bio_book_remove_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('date', models.DateField(verbose_name='дату поступления')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='цена')),
                ('unit', models.IntegerField(choices=[(1, 'шт.'), (2, 'кг.')], verbose_name='еденица измерения')),
                ('provider', models.CharField(blank=True, max_length=256, verbose_name='имя поставщика')),
                ('category', models.ManyToManyField(to='shop.category')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RenameModel(
            old_name='Bio',
            new_name='DescriptionProduct',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterField(
            model_name='descriptionproduct',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
