# Generated by Django 4.0.4 on 2022-06-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_product_remove_book_authors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptionproduct',
            old_name='author',
            new_name='product',
        ),
    ]
