# Generated by Django 4.0.4 on 2022-06-06 11:55

import django.contrib.sites.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_site'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
    ]
